version: "3.8"
services:
  web:
    build: ./src
    ports: 
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRESS_PASSWORD=${DATABASE_PASS}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: